/*
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

    1: 1
    3: 1,3
    6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?
*/
// let divisorsCount = 0;

// let acc = 0;

// for (let i = 0; i < 12500; i++) {
//     acc += i;  
//     for (let j = acc; j > 0; j--) {
//         if (acc % j == 0) {
//            divisorsCount++;
//         }
//     }
//     if (divisorsCount > 500) {
//         console.log('i = '+ i + ' divisors: '+ divisorsCount + 'acc = ' + acc  );
//         break;
//     }

//     if (divisorsCount > 200) {
//         console.log('i = '+ i + ' divisors: '+ divisorsCount + 'acc = ' + acc  );
//     }
//     divisorsCount = 0;
// }

function findNumberOfDevisors(n) {
    let currentTriangular = 0;
    let count = 0;
    while (true) {
        count++;
        currentTriangular += count;
    
        let devisorCount = 0;
        for (let i = 1; i < Math.sqrt(currentTriangular); i++) {
            if (currentTriangular % i === 0) {
                devisorCount += 2;
            }
        }
        if (Number.isInteger(Math.sqrt(currentTriangular))) {
            devisorCount++;
        }
        if (devisorCount > n) {
            return currentTriangular;
        }    
    }
} 

console.log(findNumberOfDevisors(500));