/*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

let fib = []

fib[0] = 1;
fib[1] = 1;

let sum = 0;
let n = 2;

while(fib[n - 1] < 4000000) {
    fib[n] = fib[n - 1] + fib[n - 2];    
    console.log(fib[n]);
    if (fib[n] % 2 === 0)
        sum += fib[n]    
    n++;
}

console.log("sum: " + sum);